routes/web.php
<?php

use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CompaniesController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\LocalizationController;
use App\Http\Controllers\CompanyEmployeeController;
use App\Http\Controllers\EmployeeLoginController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\SellController;
use App\Http\Controllers\SellSummaryController;
use App\Models\Employee;
use Carbon\CarbonTimeZone;
use Symfony\Component\Console\Input\Input;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::redirect('/', '/login');
Auth::routes(['register' => false]);

Route::get('lang/{lang}', [LocalizationController::class, 'lang'])->name('lang.switch');
// Route::get('timezone/{timezone}', [LocalizationController::class, 'timezone'])->name('timezone.switch');

Route::get('/dashboard',[DashboardController::class,'index']);
Route::get('dashboard/company/{company}/employee', [CompaniesController::class, 'showEmployee'])->name('company.employee');
Route::resource('/dashboard/employee', CompanyEmployeeController::class);
Route::resource('/dashboard/company', CompaniesController::class);

// Employee
Route::prefix('employee')->group(function(){
    Route::get('login/{company}', [EmployeeLoginController::class, 'login'])->name('login.employee_view');
    Route::post('login/{company}', [EmployeeLoginController::class, 'dologin'])->name('login.employee');
    Route::post('logout', [EmployeeLoginController::class, 'dologin'])->name('employee.logout')->middleware('auth:employee');
    Route::get('dashboard', [EmployeeController::class, 'index'])->name('employee.dashboard');
    Route::get('list', [EmployeeController::class, 'show']);
});

// Item
Route::resource('/dashboard/item', ItemController::class);

// Sell
Route::resource('/dashboard/sell', SellController::class);

Route::resource('/dashboard/sellsummary', SellSummaryController::class);

app/Models/Item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function sell()
    {
        return $this->hasMany(Sell::class);
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        return view('dashboard.index',[
            'title' => 'Dashboard'
        ]);
    }
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Models\Item;
use Illuminate\Http\Request;

class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(Request $request)
    {
        $page = $request->paginate;

        if($request->filter){
            if($request->filter == 'name') {
                $items = Item::where('name', 'like', "%$request->string%")->latest()->paginate($page)->withQueryString();
            }
            if($request->filter == 'price') {
                $items = Item::where('price', 'like', "%$request->string%")->latest()->paginate($page)->withQueryString();
            }
        }
        else {
            $items = Item::latest()->paginate($request->get('paginate'));
        }
        return view ('dashboard.item.index', compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.item.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'price' => 'required',
        ]);

        $item = Item::create($request->all());
        return redirect()->route('item.index', compact('item'))->with('success', __('flash.itemCreated'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Item $item)
    {
        return view('dashboard.item.detail', compact('item'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Item $item)
    {
        return view('dashboard.item.update', compact('item'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Item $item)
    {
        $request->validate([
            'name' => 'required',
            'price' => 'required',
        ]);

        $item->update($request->all());
        return redirect()->route('item.index', compact('item'))->with('success', __('flash.itemCreated'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Item $item)
    {
        $item->delete();
        return redirect()->route('item.index')->with('success', __('flash.itemRemoved'));
    }
}

resources/views/dashboard/item/create.blade.php
@extends('dashboard.layouts.main')

@section('container')
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-7">
                <form action="{{ route('item.store') }}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group mb-3">
                        <label for="name">{{ __('message.item_name') }}</label>
                        <input type="text" class="form-control" id="name" name="name" placeholder="{{ __('message.item_name') }}" autocomplete="off" value="{{ old('name') }}">
                        @error('name')
                            <div class="text-danger">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group mb-3">
                        <label for="price">{{__("message.price")}}</label>
                        <input type="text" class="form-control" id="price" name="price" placeholder="{{ __('message.price') }}" autocomplete="off" value="{{ old('price') }}">
                        @error('price')
                            <div class="text-danger">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
    <script>
    </script>
@endsection

resources/views/dashboard/item/detail.blade.php
@extends('dashboard.layouts.main')

@section('container')
    <div class="card">
        <div class="card-header">
            <h3 class="card-title text-uppercase font-weight-bold">{{ $item->name }}</h3>
            <div class="card-tools">
                {{-- <a href="{{ route('company.employee', $company) }}">{{ __('View Company Employee') }}</a> --}}
            </div>
        </div>
        <div class="card-body">
            <img class="card-img-top mr-4" src="{{ asset('/img/boxes.jpg') }}" style="width:150px; float: left;"></td>
            <ul class="mt-5">
                <li>{{__("name")}} : {{ $item->name }}</li>
                <li>{{__("price")}} : {{ $item->price }}</li>
            </ul>
        </div>
    </div>
@endsection

resources/views/dashboard/item/index.blade.php
@extends('dashboard.layouts.main')

@section('container')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Item List</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                  <li class="breadcrumb-item"><a href="#">Home</a></li>
                  <li class="breadcrumb-item active">Item List</li>
                </ol>
              </div>
        </div>
    </div>
</div>
    <div class="content">
        <div class="container-fluid ">
            <div class="row card-header" style="background:white">
                <div class="col-lg-10 justify-content-center">
                    <div class="row pb-2">
                        <div class="col ml-2">
                            <a href="/dashboard/item/create" class="text-white"><button type="button" class="btn btn-dark">{{ __('message.add_item') }}</a></button>
                            <div class="row">
                                <div class="col-md-12">
                                    <label for="filter" class="form-label">{{__('message.filter')}}</label>
                                    <form action="/dashboard/item" method="GET">
                                        <select id="filter" class="form-control filter" name="filter">
                                            @if (request('filter'))
                                                <option value="{{ request('filter') }}" selected>{{__('message.selected')}} ({{ ucfirst(request('filter'))}})</option>
                                            @else
                                                <option value="" selected>Default</option>
                                            @endif
                                                <option value="">Default</option>
                                                <option value="name">{{__('message.name')}}</option>
                                                <option value="price">{{__('message.price')}}</option>
                                        </select>
                                        <div class="form-group">
                                            <select name="paginate" id="paginate">
                                                @if (request('paginate'))
                                                    <option value="{{ request('paginate') }}" selected>{{ ucfirst(request('paginate'))}} {{__('message.pages')}}</option>
                                                @else
                                                    <option value="15" selected>15 {{__('message.pages')}}(Default)</option>
                                                @endif
                                                    <option value="10">10 {{__('message.pages')}}</option>
                                                    <option value="15">15 {{__('message.pages')}}(Default)</option>
                                                    <option value="20">20 {{__('message.pages')}}</option>
                                                    <option value="25">25 {{__('message.pages')}}</option>
                                                    <option value="50">50 {{__('message.pages')}}</option>
                                            </select>
                                        </div>
                                        <div class="input-group mb-3">
                                            <input name='string' type="text" class="form-control" placeholder="Type Here" aria-label="Type Here" aria-describedby="button-addon2">
                                            <button class="btn btn-outline-secondary" type="submit" id="button-addon2">{{__('message.search')}}</button>
                                          </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    @if($message = Session::has('success'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            {!! session('success') !!}
                            <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @endif
                    <table id="item" class="display table table-bordered table-striped">
                        <thead class="table">
                            <tr>
                                <th>No</th>
                                <th>{{ __('message.name') }}</th>
                                <th>{{__('message.price')}}</th>
                                <th>Create at</th>
                                <th>{{ __('Action') }}</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($items as $item)
                                <tr>
                                    <td>{{$loop->iteration}}</td>
                                    <td>{{$item->name}}</td>
                                    <td>Rp. {{number_format($item->price, 0, ',', '.')}}</td>
                                    <td>{{$item->created_at}}</td>
                                    <td>
                                        <form class="d-inline" action="{{ route('item.destroy',$item) }}" method="post">
                                            <a href="{{ route('item.show',$item) }}" class="btn btn-info btn-sm"><i class="fas fa-eye"></i></a>
                                            <a href="{{ route('item.edit',$item) }}" class="btn btn-dark btn-sm"><i class="fa fa-pencil"></i></a>
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-danger btn-sm" onclick="return confirm('Confirm to delete data')" ><i class="fas fa-trash-alt"></i></button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    {{ $items->links() }}
@endsection

resources/views/dashboard/item/update.blade.php
@extends('dashboard.layouts.main')

@section('container')
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-7">
            <form action="{{ route('item.update', $item) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="form-group mb-3">
                    <label for="name">{{ __('message.item_name') }}</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="{{__('item_name')}}" value="{{ $item->name }}">
                    @error('name')
                        <div class="text-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="form-group mb-3">
                    <label for="price">{{__('price')}}</label>
                    <input type="text" class="form-control" id="price" name="price" placeholder="{{__('price')}}" value="{{ $item->price }}">
                    @error('price')
                        <div class="text-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary">Update</button>
            </form>
        </div>
    </div>
</div>
@endsection