routes/web.php
<?php

use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CompaniesController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\LocalizationController;
use App\Http\Controllers\CompanyEmployeeController;
use App\Http\Controllers\EmployeeLoginController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\SellController;
use App\Http\Controllers\SellSummaryController;
use App\Models\Employee;
use Carbon\CarbonTimeZone;
use Symfony\Component\Console\Input\Input;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::redirect('/', '/login');
Auth::routes(['register' => false]);

Route::get('lang/{lang}', [LocalizationController::class, 'lang'])->name('lang.switch');
// Route::get('timezone/{timezone}', [LocalizationController::class, 'timezone'])->name('timezone.switch');

Route::get('/dashboard',[DashboardController::class,'index']);
Route::get('dashboard/company/{company}/employee', [CompaniesController::class, 'showEmployee'])->name('company.employee');
Route::resource('/dashboard/employee', CompanyEmployeeController::class);
Route::resource('/dashboard/company', CompaniesController::class);

// Employee
Route::prefix('employee')->group(function(){
    Route::get('login/{company}', [EmployeeLoginController::class, 'login'])->name('login.employee_view');
    Route::post('login/{company}', [EmployeeLoginController::class, 'dologin'])->name('login.employee');
    Route::post('logout', [EmployeeLoginController::class, 'dologin'])->name('employee.logout')->middleware('auth:employee');
    Route::get('dashboard', [EmployeeController::class, 'index'])->name('employee.dashboard');
    Route::get('list', [EmployeeController::class, 'show']);
});

// Item
Route::resource('/dashboard/item', ItemController::class);

// Sell
Route::resource('/dashboard/sell', SellController::class);

Route::resource('/dashboard/sellsummary', SellSummaryController::class);

app/Models/Sell.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Sell extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function item()
    {
        return $this->belongsTo(Item::class);
    }

    public function employee()
    {
        return $this->belongsTo(Employee::class);
    }

    public function summary()
    {
        return $this->hasMany(Sell::class);
    }

    static function filter($filter,$data,$page)
    {
        return self::where("$filter", 'like', "%$data%")->latest()->paginate($page)->withQueryString();
    }

}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        return view('dashboard.index',[
            'title' => 'Dashboard'
        ]);
    }
}

app/Http/Controllers/SellController.php
<?php

namespace App\Http\Controllers;

use App\Models\Item;
use App\Models\Employee;
use App\Models\Companies;
use App\Models\Sell;
use App\Models\SellSummary;
use Illuminate\Http\Request;

class SellController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index(Request $request)
    {
        $page = $request->paginate;
        $data = $request->string;

        if($filter = $request->filter) {
            if($filter == 'price' || $filter == 'discount') {
                $sells = Sell::filter($filter,$data,$page);
            } elseif($filter == 'employee_name') {
                $sells = Employee::where('first_name', 'like', "%$data%")->latest()->paginate($page)->withQueryString();
                $id = $sells->pluck('id');
                $sells = Sell::whereIn('employee_id', $id)->latest()->paginate($page)->withQueryString();
            } elseif($filter == 'company_name') {
                $sells = Companies::where('name', 'like', "%$data%")->latest()->paginate($page)->withQueryString();
                $id = $sells->pluck('id')[0];
                $sells = Employee::where('companies_id', 'like', "$id")->latest()->paginate($page)->withQueryString();
                $id = $sells->pluck('id');
                $sells = Sell::whereIn('employee_id', $id)->latest()->paginate($page)->withQueryString();
            }
            else {
                abort(404);
            }
        } elseif($request->from) {
            $sells = Sell::whereBetween('date', [$request->get('from'), $request->get('to')])->latest()->paginate($page)->withQueryString();
        } else {
            $sells = Sell::latest()->paginate($request->get('paginate'));
        }
        return view('dashboard.sell.index', compact('sells'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.sell.create',[
            'items' => Item::all(),
            'employees' => Employee::all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Sell $sell)
    {
        $request->validate([
            'date'=> 'required',
            'discount'=> 'required',
            'price'=> 'required',
            'item_id'=> 'required',
            'employee_id'=> 'required',
        ]);
        Sell::create($request->all());
        $employee_id = $request->employee_id;

        $date = date('Y-m-d',strtotime($request->date));

        if($summary = SellSummary::where([['employee_id', $employee_id], ['date', $date]])->first()){
            $summary->update([
                'price_total' => $summary->price_total + $request->price,
                'discount_total' => $summary->discount_total + $request->discount * $request->price/ 100,
                'total' => $summary->total + $request->price - $request->discount * $request->price /100,
                'updated_at' => date('Y-m-d')
            ]);

        } else {
            SellSummary::create([
                'date' => $date,
                'employee_id' => $request->employee_id,
                'price_total' => $request->price,
                'discount_total' => $request->discount * $request->price/ 100,
                'total' => $request->price - $request->discount * $request->price /100
            ]);
        }
        return redirect()->route('sell.index')->with('success',__('flash.sellCreated'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Sell $sell)
    {
        return view('dashboard.sell.detail', compact('sell'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Sell $sell)
    {
        return view('dashboard.sell.update', compact('sell'),[
            'items'=>Item::all(),
            'employees'=>Employee::all(),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Sell $sell, SellSummary $summary)
    {
        $employee_id = Sell::all()->first();

        $input = $request->validate([
            'date'=> 'required',
            'discount'=> 'required',
            'price'=> 'required',
            'item_id'=> 'required',
            'employee_id'=> 'required',
        ]);
        $input['price'] = $sell->price + $request->price;
        $input['discount'] = $sell->discount + $request->discount;

        $sell->update($input);
        $employee_id = $request->employee_id;

        $date = date('Y-m-d',strtotime($request->date));

        if($summary = SellSummary::where([['employee_id', $employee_id], ['date', $date]])->first()){
            $summary->update([
                'price_total' => $summary->price_total + $request->price,
                'discount_total' => $summary->discount_total + $request->discount * $request->price/ 100,
                'total' => $summary->total + $request->price - $request->discount * $request->price /100,
                'updated_at' => date('Y-m-d')
            ]);

        } else {
            SellSummary::create([
                'date' => $date,
                'employee_id' => $request->employee_id,
                'price_total' => $request->price,
                'discount_total' => $request->discount * $request->price/ 100,
                'total' => $request->price - $request->discount * $request->price /100
            ]);
        }

        return redirect()->route('sell.index', compact('sell'))->with('success', __('flash.sellCreated'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Sell $sell)
    {
        $sell->delete();
        return redirect()->route('sell.index')->with('success', __('flash.sellRemoved'));
    }
}

resources/views/dashboard/sell/create.blade.php
@extends('dashboard.layouts.main')

@section('container')
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-7">
                <form action="{{ route('sell.store') }}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="mb-3">
                    <label for="item_name" class="form-label">{{__('message.item_name')}}</label>
                        <select id="item_name" class="form-control item_name" name="item_id">
                            @foreach ($items as $item)
                                @if (old('item')==$item->id)
                                    <option value="{{$item->id}}" selected>{{$item->name}}</option>
                                @else
                                    <option value="{{$item->id}}" selected>{{$item->name}}</option>
                                @endif
                            @endforeach
                        </select>
                    </div>
                    <div class="mb-3">
                    <label for="employee" class="form-label">{{__('message.employee')}}</label>
                        <select id="employee" class="form-control employee" name="employee_id">
                            @foreach ($employees as $employee)
                                @if (old('employee') == $employee->id)
                                    <option value="{{$employee->id}}" selected>{{$employee->first_name}} {{$employee->last_name}}</option>
                                @else
                                    <option value="{{$employee->id}}" selected>{{$employee->first_name}} {{$employee->last_name}}</option>
                                @endif
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="date">{{__('message.sell_date')}}</label>
                        <input type="date", id="date" name="date" class="form-control">
                        @error('date')
                            <div class="text-danger">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group mb-3">
                        <label for="discount">{{ __('message.discount') }}</label>
                        <input type="text" class="form-control" id="discount" name="discount" placeholder="{{ __('message.item_discount') }}" autocomplete="off" value="{{ old('discount') }}">
                        @error('discount')
                            <div class="text-danger">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group mb-3">
                        <label for="price">{{__('message.price')}}</label>
                        <input type="text" class="form-control" id="price" name="price" placeholder="{{ __('message.price') }}" autocomplete="off" value="{{ old('price') }}">
                        @error('price')
                            <div class="text-danger">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
    <script>
    </script>
@endsection

resources/views/dashboard/sell/detail.blade.php
@extends('dashboard.layouts.main')

@section('container')
    <div class="card">
        <div class="card-header">
            <h3 class="card-title text-uppercase font-weight-bold">{{ $sell->item->name }}</h3>
            <div class="card-tools">
                {{-- <a href="{{ route('company.employee', $company) }}">{{ __('View Company Employee') }}</a> --}}
            </div>
        </div>
        <div class="card-body">
            <img class="card-img-top mr-4" src="{{ asset('/img/boxes.jpg') }}" style="width:150px; float: left;"></td>
            <h1>{{__("message.name")}} : {{ $sell->item->name }}</h1>
            <ul class="mt-2">
                <li>{{__("message.sell_date")}} : {{ $sell->date }}</li>
                <li>{{__('message.price')}} : {{ $sell->price}}</li>
                <li>{{__('message.discount')}} : {{ $sell->discount}}</li>
                <li>{{__('message.employee')}} : {{ $sell->employee->first_name}} {{$sell->employee->last_name}}</li>
            </ul>
        </div>
    </div>
@endsection

resources/views/dashboard/sell/index.blade.php
@extends('dashboard.layouts.main')

@section('container')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Item Sold</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                  <li class="breadcrumb-item"><a href="#">Home</a></li>
                  <li class="breadcrumb-item active">Item Sold</li>
                </ol>
              </div>
        </div>
    </div>
</div>
    <div class="content">
        <div class="container-fluid ">
            <div class="row card-header" style="background:white">
                <div class="col-lg-10 justify-content-center">
                    <div class="row pb-2">
                        <div class="col ml-2">
                            <a href="/dashboard/sell/create" class="text-white"><button type="button" class="btn btn-dark">{{ __('message.add_item_sold') }}</a></button>
                            <div class="row">
                                <div class="col-md-12">
                                    <label for="filter" class="form-label">{{__('message.filter')}}</label>
                                    <form action="/dashboard/sell" method="GET">
                                        <select id="filter" class="form-control filter" name="filter">
                                            @if (request('filter'))
                                                <option value="{{ request('filter') }}" selected>{{__('message.selected')}} ({{ ucfirst(request('filter'))}})</option>
                                            @else
                                                <option value="" selected>Default</option>
                                            @endif
                                                <option value="">Default</option>
                                                <option value="price">{{__('message.price')}}</option>
                                                <option value="company_name">{{__('message.company')}}</option>
                                                <option value="employee_name">{{__('message.employee_name')}}</option>
                                                <option value="discount">{{__('message.discount')}}</option>
                                        </select>
                                        <div>
                                            <div class="form">
                                                <label for="from">{{__('message.from')}}</label>
                                                <input type="date", id="from" name="from" class="form-control" value="{{date('Y-m-d')}}">&nbsp;
                                            </div>
                                            <div class="form">
                                                <label for="to">{{__('message.to')}}</label>
                                                <input type="date", id="to" name="to" class="form-control"value="{{date('Y-m-d')}}">&nbsp;
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <select name="paginate" id="paginate">
                                                @if (request('paginate'))
                                                    <option value="{{ request('paginate') }}" selected>{{ ucfirst(request('paginate'))}} {{__('message.pages')}}</option>
                                                @else
                                                    <option value="15" selected>15 {{__('message.pages')}}(Default)</option>
                                                @endif
                                                    <option value="10">10 {{__('message.pages')}}</option>
                                                    <option value="15">15 {{__('message.pages')}}(Default)</option>
                                                    <option value="20">20 {{__('message.pages')}}</option>
                                                    <option value="25">25 {{__('message.pages')}}</option>
                                                    <option value="50">50 {{__('message.pages')}}</option>
                                            </select>
                                    </div>
                                        <div class="input-group mb-3">
                                            <input name='string' type="text" class="form-control" placeholder="Type Here" aria-label="Type Here" aria-describedby="button-addon2" value="{{ request('string') }}">
                                            <button class="btn btn-outline-secondary" type="submit" id="button-addon2">{{__('message.search')}}</button>
                                          </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    @if($message = Session::has('success'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            {!! session('success') !!}
                            <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @endif
                    <table id="item" class="display table table-bordered table-striped">
                        <thead class="table">
                            <tr>
                                <th>No</th>
                                <th>{{__("message.sell_date")}}</th>
                                <th>{{ __('message.item_name') }}</th>
                                <th>{{ __('message.price') }}</th>
                                <th>{{ __('message.discount') }}</th>
                                <th>{{ __('message.employee_name') }}</th>
                                <th>{{ __('message.action') }}</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($sells as $sell)
                            <tr>
                                <td>{{$loop->iteration}}</td>
                                <td>{{$sell->date}}</td>
                                <td>{{$sell->item->name}}</td>
                                <td>Rp. {{number_format($sell->price, 0, ',' , '.')}}</td>
                                <td>{{number_format($sell->discount, 0, ',','.')}}%</td>
                                <td>{{$sell->employee->first_name}} {{$sell->employee->last_name}}</td>
                                <td>
                                    <form class="d-inline" action="{{ route('sell.destroy',$sell) }}" method="post">
                                        <a href="{{ route('sell.show',$sell) }}" class="btn btn-info btn-sm"><i class="fas fa-eye"></i></a>
                                        <a href="{{ route('sell.edit',$sell) }}" class="btn btn-dark btn-sm"><i class="fa fa-pencil"></i></a>
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-danger btn-sm" onclick="return confirm('Confirm to delete data')" ><i class="fas fa-trash-alt"></i></a>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    {{$sells->links()}}
@endsection

resources/views/dashboard/sell/update.blade.php
@extends('dashboard.layouts.main')

@section('container')
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-7">
            <form action="{{ route('sell.update', $sell) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="mb-3">
                    <label for="item_name" class="form-label">{{__('message.item_name')}}</label>
                        <select id="item_name" class="form-control item_name" name="item_id">
                            @foreach ($items as $item)
                                @if ($sell->item->id == $item->id)
                                    <option value="{{$item->id}}" selected>{{$item->name}}</option>
                                @else
                                    <option value="{{$item->id}}" selected>{{$item->name}}</option>
                                @endif
                            @endforeach
                        </select>
                    </div>
                    <div class="mb-3">
                    <label for="employee" class="form-label">{{__('message.employee')}}</label>
                        <select id="employee" class="form-control employee" name="employee_id">
                            @foreach ($employees as $employee)
                                @if ($sell->employee->id == $employee->id)
                                    <option value="{{$employee->id}}" selected>{{$employee->first_name}} {{$employee->last_name}}</option>
                                @else
                                    <option value="{{$employee->id}}">{{$employee->first_name}} {{$employee->last_name}}</option>
                                @endif
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="date">{{__('message.sell_date')}} </label>
                        <input type="date", id="date" name="date" class="form-control" value="{{ old('date', date('Y-m-d')) }}">
                        @error('discount')
                            <div class="text-danger">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group mb-3">
                        <label for="discount">{{ __('message.discount') }} ({{$sell->discount}})</label>
                        <input type="text" class="form-control" id="discount" name="discount" placeholder="{{ __('message.item_discount') }}" autocomplete="off" value="0">
                        @error('discount')
                            <div class="text-danger">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group mb-3">
                        <label for="price">{{__('message.price')}} ({{$sell->price}})</label>
                        <input type="text" class="form-control" id="price" name="price" placeholder="{{ __('message.price') }}" autocomplete="off" value="0">
                        @error('price')
                            <div class="text-danger">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                <button type="submit" class="btn btn-primary">Update</button>
            </form>
        </div>
    </div>
</div>
@endsection