routes/web.php
<?php

use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CompaniesController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\LocalizationController;
use App\Http\Controllers\CompanyEmployeeController;
use App\Http\Controllers\EmployeeLoginController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\SellController;
use App\Http\Controllers\SellSummaryController;
use App\Models\Employee;
use Carbon\CarbonTimeZone;
use Symfony\Component\Console\Input\Input;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::redirect('/', '/login');
Auth::routes(['register' => false]);

Route::get('lang/{lang}', [LocalizationController::class, 'lang'])->name('lang.switch');
// Route::get('timezone/{timezone}', [LocalizationController::class, 'timezone'])->name('timezone.switch');

Route::get('/dashboard',[DashboardController::class,'index']);
Route::get('dashboard/company/{company}/employee', [CompaniesController::class, 'showEmployee'])->name('company.employee');
Route::resource('/dashboard/employee', CompanyEmployeeController::class);
Route::resource('/dashboard/company', CompaniesController::class);

// Employee
Route::prefix('employee')->group(function(){
    Route::get('login/{company}', [EmployeeLoginController::class, 'login'])->name('login.employee_view');
    Route::post('login/{company}', [EmployeeLoginController::class, 'dologin'])->name('login.employee');
    Route::post('logout', [EmployeeLoginController::class, 'dologin'])->name('employee.logout')->middleware('auth:employee');
    Route::get('dashboard', [EmployeeController::class, 'index'])->name('employee.dashboard');
    Route::get('list', [EmployeeController::class, 'show']);
});

// Item
Route::resource('/dashboard/item', ItemController::class);

// Sell
Route::resource('/dashboard/sell', SellController::class);

Route::resource('/dashboard/sellsummary', SellSummaryController::class);

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Employee extends Authenticatable
{
    use HasFactory;


    protected $guarded = ['id'];
    protected $with = ['companies'];

    protected $hidden = [
        'password'
       ];

    public function companies()
    {
        return $this->belongsTo(Companies::class);
    }

    public function sells()
    {
        return $this->hasMany(Sell::class);
    }

    public function sellsummary()
    {
        return $this->hasMany(SellSummary::class);
    }

    public function index()
    {
        return view('dashboard.company.users.index');
    }


}

app/Http/Controllers/CompaniesController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Companies;
use Illuminate\Http\Request;
use Faker\Provider\ar_JO\Company;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use App\Notifications\CompanyCreated;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Notification;

class CompaniesController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $page = $request->paginate;

        if($request->filter){
            if($request->filter == 'name') {
                $companies = Companies::where('name', 'like', "%$request->string%")->latest()->paginate($page)->withQueryString();
            }
            elseif($request->filter == 'email'){
                $companies = Companies::where('email','like', "%$request->string%")->latest()->paginate($page)->withQueryString();
            }
            elseif($request->filter == 'website'){
                $companies = Companies::where('website','like', "%$request->string%")->latest()->paginate($page)->withQueryString();
            }
        }
        else {
            $companies = Companies::latest()->paginate($request->get('paginate'));

        };

        return view('dashboard.company.index', compact('companies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.company.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = Auth::user(); // Retrieve the currently authenticated user...
        $id = Auth::id([]); // Retrieve the currently authenticated user's ID...

        $request->validate([
            'name' => 'required',
            'email' => 'required',
            'website' => 'required',
            'logo' => ' image|dimensions:min_width=100,min_height=100',
        ]);


        $input = $request->all();

        if ($request->file('logo')) {
            $input['logo'] = $request->file('logo')->store('logo');
        } else {
            $input['logo'] = "default.png";
        }
        $input['created_by_id'] = $id;
        $input['updated_by_id'] = $id;

        $test = Companies::create($input);
        $user = User::first();

        $createdData = [
            'header' => 'New Company has been created!',
            'body' => 'New company named ' . $request->get('name') .  ' has been created!',
            'text' => 'Go to Company',
            'url' => url('/dashboard/company'),
            'thankyou' => 'Thank you'
        ];

        $user->notify(new CompanyCreated($createdData));

        return redirect()->route('company.index')->with('success', __('flash.companyCreated'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Companies  $companies
     * @return \Illuminate\Http\Response
     */
    public function show(Companies $company)
    {
        return view('dashboard.company.detail', compact('company'));
    }

    public function showEmployee(Companies $company)
    {
        return view('dashboard.company.employee')->with('employees', $company->employee);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Companies  $companies
     * @return \Illuminate\Http\Response
     */
    public function edit(Companies $company)
    {

        return view('dashboard.company.update', compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Companies  $companies
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Companies $company)
    {
        $user = Auth::user(); // Retrieve the currently authenticated user...
        $id = Auth::id([]); // Retrieve the currently authenticated user's ID...

        $request->validate([
            'name' => 'required',
            'logo' => 'image|dimensions:min_width=100,min_height=100',
        ]);

        $input = $request->all();

        if ($request->file('logo')) {
            if($company['logo'] != 'default.png') Storage::delete($company['logo']);
            $input['logo'] = $request->file('logo')->store('logo');
        } else {
            unset($input['logo']);
        }
        $input['updated_by_id'] = $id;

        $company->update($input);

        return redirect()->route('company.index')->with('success', __('flash.companyUpdated'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Companies  $companies
     * @return \Illuminate\Http\Response
     */
    public function destroy(Companies $company)
    {
        $company->employee()->delete();
        if($company['logo'] != 'default.png') Storage::delete($company['logo']);
        $company->delete();

        return redirect()->route('company.index')->with('success', __('flash.companyRemoved'));
    }

}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Employee;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:employee');
    }
    public function index()
    {
        return view('dashboard.employee.index');
    }
    public function show(Request $request)
    {
        $page = $request->paginate;
        $company_id = auth()->user()->companies_id;

        if($request->filter){
            if($request->filter == 'first_name') {
                $employees = Employee::where(['company_id', $company_id],'first_name', 'like', "%$request->string%")->latest()->paginate($page)->withQueryString();
            }
            elseif($request->filter == 'last_name'){
                $employees = Employee::where(['company_id', $company_id],'last_name','like', "%$request->string%")->latest()->paginate($page)->withQueryString();
            }
            elseif($request->filter == 'companies_id'){
                $employees = Employee::where(['company_id', $company_id],'companies_id','like', "%$request->string%")->latest()->paginate($page)->withQueryString();
            }
            elseif($request->filter == 'email'){
                $employees = Employee::where(['company_id', $company_id],'email','like', "%$request->string%")->latest()->paginate($page)->withQueryString();
            }
            elseif($request->filter == 'phone'){
                $employees = Employee::where(['company_id', $company_id],'phone','like', "%$request->string%")->latest()->paginate($page)->withQueryString();
            }
        }
        else {
            $employees = Employee::where('companies_id', $company_id)->paginate($request->get('paginate'));
        }
        return view('dashboard.employee.list', compact('employees'));
    }
}

resources/views/dashboard/company/employee/create.blade.php
@extends('dashboard.layouts.main')

@section('container')
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-7">
                <form action="{{ route('employee.store') }}" method="post" enctype="multipart/form-data">
                    @csrf
                    <input type="hidden" name="companies_id" value="{{ $company_id }}">
                    <div class="form-group mb-3">
                        <label for="first_name">{{ __('First Name') }}</label>
                        <input type="text" class="form-control" id="first_name" name="first_name" placeholder="First Name" autocomplete="off" value="{{ old('first_name') }}">
                        @error('first_name')
                            <div class="text-danger">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group mb-3">
                        <label for="last_name">{{ __('Last Name') }}</label>
                        <input type="text" class="form-control" id="last_name" name="last_name" placeholder="Last Name" autocomplete="off" value="{{ old('last_name') }}">
                        @error('last_name')
                            <div class="text-danger">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group mb-4">
                        <label for="email">Email</label>
                        <input type="text" class="form-control" id="email" name="email" placeholder="example@example.com" autocomplete="off" value="{{ old('email') }}">
                        @error('email')
                            <div class="text-danger">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group mb-4">
                        <label for="phone">{{ __('Phone number') }}</label>
                        <input type="text" class="form-control" id="phone" name="phone" placeholder="12345678" autocomplete="off" value="{{ old('phone') }}">
                        @error('phone')
                            <div class="text-danger">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group mb-4">
                        <label for="password">{{ __('Password') }}</label>
                        <input type="text" class="form-control" id="password" name="password" placeholder="qwerty" autocomplete="off" value="{{ old('password') }}">
                        @error('password')
                            <div class="text-danger">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/company/employee/detail.blade.php
@extends('dashboard.layouts.main')

@section('container')
    <div class="card">
        <div class="card-header">
            <h3 class="card-title text-uppercase font-weight-bold">{{ $employee->first_name }}  {{ $employee->last_name }}</h3>
            <div class="card-tools">
                <span class="badge badge-primary">Option</span>
            </div>
        </div>
        <div class="card-body">
            <img src="/img/user.png" class="card-img-top mr-4" style="width:150px; float:left;" alt="...">
            <ul class="mt-5">
                <li>
                    {{ __('Company Name') }} : <a href="/dashboard/company/{{ $employee->companies->id }}" class="text-uppercase">{{ $employee->companies->name }}</a>
                </li>
                <li>Email : {{ $employee->email }}</li>
                <li>Phone : {{ $employee->phone }}</li>
            </ul>
        </div>
    </div>
@endsection

resources/views/dashboard/company/employee/index.blade.php
@extends('dashboard.layouts.main')

@section('container')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Employee</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                  <li class="breadcrumb-item"><a href="#">Home</a></li>
                  <li class="breadcrumb-item active">Employee</li>
                </ol>
              </div>
        </div>
    </div>
</div>
<div class="content">
    <div class="container ml-2" style="background:white">
        <div class="col-lg-12">
            @if($message = Session::has('success'))
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {!! session('success') !!}
                    <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endif
            <label for="filter" class="form-label">{{__('message.filter')}}</label>
            <form action="/dashboard/employee" method="GET">
                <select id="filter" class="form-control filter" name="filter">
                    @if (request('filter'))
                        <option value="{{ request('filter') }}" selected>{{__('message.selected')}} ({{ ucfirst(request('filter'))}})</option>
                    @else
                        <option value="" selected>Default</option>
                    @endif
                        <option value="">Default</option>
                        <option value="first_name">{{__('message.first_name')}}</option>
                        <option value="last_name">{{__('message.last_name')}}</option>
                        <option value="companies_id">{{__('message.companies_id')}}</option>
                        <option value="email">{{__('message.email')}}</option>
                        <option value="phone">{{__('message.phone')}}</option>
                </select>
                <div class="form-group">
                    <select name="paginate" id="paginate">
                        @if (request('paginate'))
                            <option value="{{ request('paginate') }}" selected>{{ ucfirst(request('paginate'))}} {{__('message.pages')}}</option>
                        @else
                            <option value="15" selected>15 {{__('message.pages')}}(Default)</option>
                        @endif
                            <option value="10">10 {{__('message.pages')}}</option>
                            <option value="15">15 {{__('message.pages')}}(Default)</option>
                            <option value="20">20 {{__('message.pages')}}</option>
                            <option value="25">25 {{__('message.pages')}}</option>
                            <option value="50">50 {{__('message.pages')}}</option>
                    </select>
                </div>
                <div class="input-group mb-3">
                    <input name='string' type="text" class="form-control" placeholder="Type Here" aria-label="Type Here" aria-describedby="button-addon2">
                    <button class="btn btn-outline-secondary" type="submit" id="button-addon2">{{__('message.search')}}</button>
                  </div>
                  <select name="timezone" id="timezone" class="form-control timezone">
                    @if (request('timezone'))
                        <option value="{{ request('timezone') }}" selected>{{ ucfirst(request('timezone'))}}</option>
                    @else
                        <option value="" selected>{{__('message.time_zone')}}(Default)</option>
                    @endif
                        <option value="">Default</option>
                        <option value="Asia/Jakarta">Jakarta</option>
                        <option value="Asia/Singapore">Singapore</option>
                        <option value="Asia/Tokyo">Tokyo</option>
                </select>
            </form>
            <table id="employee" class="display table table-bordered table-striped mt-2">
                <thead class="table">
                    <tr>
                        <th>No</th>
                        <th>{{ __('First Name') }}</th>
                        <th>{{ __('Last Name') }}</th>
                        <th>{{ __('Company Name') }}</th>
                        <th>Email</th>
                        <th>{{ __('Phone') }}</th>
                        <th>{{ __('Created At') }}</th>
                        <th>{{ __('Action') }}</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($employees as $employee)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $employee->first_name }}</td>
                        <td>{{ $employee->last_name }}</td>
                        <td><a href="/dashboard/company/{{ $employee->companies->id }}">{{ $employee->companies->name }}</a></td>
                        <td>{{ $employee->email }}</td>
                        <td>{{ $employee->phone }}</td>
                        <td>{{ carbon\Carbon::parse($employee->created_at)->setTimezone(request('timezone')) }}</td>
                        <td>
                            <form class="d-inline" action="{{ route('employee.destroy',$employee) }}" method="post">
                                <a href="{{ route('employee.show',$employee) }}" class="btn btn-info btn-sm"><i class="fas fa-eye"></i></a>
                                <a href="{{ route('employee.edit',$employee) }}" class="btn btn-dark btn-sm"><i class="fa fa-pencil"></i></a>
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger btn-sm" onclick="return confirm('Confirm to delete data')" ><i class="fas fa-trash-alt"></i></a>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            </div>
        </div>
    </div>
</div>
<script>
</script>

{{ $employees->links() }}
@endsection

resources/views/dashboard/company/employee/update.blade.php
@extends('dashboard.layouts.main')

@section('container')
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-7">
            <form action="{{ route('employee.update',$employee) }}" method="post" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="form-group mb-3">
                    <label for="first_name">First Name</label>
                    <input type="text" class="form-control" id="first_name" name="first_name" placeholder="First Name" autocomplete="off" value="{{ $employee->first_name }}" required>
                    @error('first_name')
                        <div class="text-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="form-group mb-3">
                    <label for="last_name">Last Name</label>
                    <input type="text" class="form-control" id="last_name" name="last_name" placeholder="Last Name" autocomplete="off" value="{{ $employee->last_name }}" required>
                    @error('last_name')
                        <div class="text-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="form-group mb-4">
                    <label for="email">Email</label>
                    <input type="text" class="form-control" id="email" name="email" placeholder="example@example.com" autocomplete="off" value="{{ $employee->email }}">
                    @error('email')
                        <div class="text-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="form-group mb-4">
                    <label for="phone">Phone number</label>
                    <input type="text" class="form-control" id="phone" name="phone" placeholder="123456789" autocomplete="off" value="{{ $employee->phone }}">
                    @error('phone')
                        <div class="text-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <div class="form-group mb-4">
                    <label for="password">Password</label>
                    <input type="text" class="form-control" id="password" name="password" placeholder="123456789" autocomplete="off" value="{{ $employee->password }}">
                    @error('password')
                        <div class="text-danger">
                            {{ $message }}
                        </div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
@endsection